language: php
php:
- 5.4
- 5.5
- 5.6
- 7.0
- 7.4
- 8.1
- hhvm
matrix:
  allow_failures:
  - php: hhvm
before_script: composer update --dev
script: php vendor/phpunit/phpunit/phpunit
notifications:
  slack: eduid:JJc9VL5htezKWr40wEUTug8K
